### ISSUE TITLE
Reverse sorting?

### ISSUE THREAD

**Issue by cloudunicorn** [jlord/sheetsee.js#104]
Hi there, noob question - is there a quick way to reverse the order of the table on the Pocket Sheetsee? It lists the last article first on the site, hoping to list the 1st as we're using it for a different use case.

Thanks!

**Comment by cloudunicorn** [comment]
Hm, no longer supported, eh? Can anyone point me to the best place to get this answered?

Thanks!

**Comment by deviljoker1** [comment]
Yell give me just a bit I'll will help you

**Comment by deviljoker1** [comment]
![162eu8-1](https://cloud.githubusercontent.com/assets/22898620/19509806/78045692-95ae-11e6-8e2d-f419399173e7.gif)

**Comment by deviljoker1** [comment]
Tell more about what your  #developing some I've design tried to some different and way better in the end.
Thanks

**Comment by deviljoker1** [comment]
Hi octocat

**Comment by cloudunicorn** [comment]
What?

**Comment by jlord** [comment]
Before you use sheets you can `.reverse()` your data coming from Tabletop and that should do the trick ✨
