### ISSUE TITLE
GID Option

### ISSUE THREAD

**Issue by haivipreal** [jlord/sheetsee.js#116]
Tks much for your great script. It helps me a lot but I have to create a new spreadsheet for new data because the script choose data from Sheet1 in default. (I do not want to create a new column in same sheet with other header name because the script will pull all the data slowly)

The sheetrock script has this option but I love to use Sheetsee script. I'm just newbie so please advise me. Tks a millions.

Hai

**Comment by jlord** [comment]
The tabletop library allows you to use multiple sheets from your spreadsheet. That might be what you're looking for? 

→ https://github.com/jsoma/tabletop#sheets
