### ISSUE TITLE
tabletop 1.3.4.js

### ISSUE THREAD

**Issue by Fredlumiere** [jlord/sheetsee.js#127]
Hi Jessica,

We were using your old version of sheetsee.js for our website:

http://www.hpvepidemic.com/testimonials

Were linking to:
<script type='text/javascript' src='http://jlord.us/sheetsee.js/js/tabletop1.3.4.js'></script>
<script type='text/javascript' src='http://jlord.us/sheetsee.js/js/sheetsee.js'></script>

It looks like you released a new version. Could you tell me where we could find the old version please?

Thanks!!!

I will send you a free copy of the film of course :)

Frederic
fred@hpvepidemic.com

**Comment by jlord** [comment]
Hi!

The old version should be in the `js` directory as of this commit in the history:

https://github.com/jlord/sheetsee.js/tree/ce3008783aae6f2481163132ea06f1074043b026

You'll want to copy it and serve it locally from your site. That should do the trick!

**Comment by Fredlumiere** [comment]
Super - worked great.

Thank you!!!

Fred

**Comment by jlord** [comment]
Awesome! ✨

**Comment by Fredlumiere** [comment]
Hi Jessica,

Did anything change? Even though I’m still using the old version (stored on my site), the dynamic filtering stopped working:

https://www.hpvepidemic.com/testimonials <https://www.hpvepidemic.com/testimonials>

Fred

Fred | APIANT

**Comment by Fredlumiere** [comment]
Nevermind sorry - it works.

Fred | APIANT
