### ISSUE TITLE
spreadsheet.glitch.me doesn't seem to be working for me ? 

### ISSUE THREAD

**Issue by a-eid** [jlord/sheetsee.js#140]
I have been trying to use `spreadsheet.glitch.me`

but it is returning the following error 
```
failed to start application on spreadsheet.glitch.me

This is most likely because your project has a code error.
Check your project logs, fix the error and try again.
```

spreadsheet link is `https://docs.google.com/spreadsheets/d/1vIL3pCkExFNnfMq44uNlfZR_md4dpsL_e7Y3hn7ryJo/edit#gid=0` 

could somebody tell me why isn't it parsing it .

**Comment by jlord** [comment]
I'm not sure, it is working for other spreadsheets. Have you 'published to the web' your spreadsheet?

**Comment by a-eid** [comment]
@jlord  I created another speadsheet and weirdly it worked perfectly , I have another quick question , when I try to `fetch` I get a `CORS` error , how to bypass that ?

**Comment by jlord** [comment]
@a-eid give it a try again, it should be fixed now (thanks to @muan!)

**Comment by a-eid** [comment]
@jlord  @muan Thank you
