### ISSUE TITLE
Typo (sort of)

### ISSUE THREAD

**Issue by digitalii** [jlord/sheetsee.js#167]
On:  http://jlord.us/sheetsee.js/docs/about.html

Reads:  Thanks to Code for America for providing the platform me to build the first version of sheetsee.js for Macon, Georgia.

Should read:  Thanks to Code for America for providing the platform **_for_** me to build the first version of sheetsee.js for Macon, Georgia.

Thanks for the great work.  I'm about to give it a try.

**Comment by jlord** [comment]
Awesome, thank you for finding this! ✨
