### ISSUE TITLE
I also use a Python script for backing up the Google Spreadsheet daily by reading in the spreadsheet, writing each row to a CSV file, and then saving it with a new timestamp.

### ISSUE THREAD

**Issue by osamahassani05355881581** [jlord/sheetsee.js#354]
I also use a Python script for backing up the Google Spreadsheet daily by reading in the spreadsheet, writing each row to a CSV file, and then saving it with a new timestamp. 

Do you think that the building of the support desk along with the automation of backups would make for a good blog post? I can also add in some D3 charts to show perhaps the breakdown of complete vs incomplete data. I could also add a column if for the type of issue and then show a breakdown of the types as well?

_Originally posted by @mjhea0 in https://github.com/jlord/sheetsee.js/issues/47#issuecomment-44542542_

**Comment by jawomg** [comment]
R

**Comment by jawomg** [comment]
> ฉันยังใช้สคริปต์ Python เพื่อสำรองข้อมูลสเปรดชีตของ Google ทุกวันด้วยการอ่านสเปรดชีต เขียนแต่ละแถวลงในไฟล์ CSV แล้วบันทึกด้วยการประทับเวลาใหม่
> 
> คุณคิดว่าการสร้างแผนกสนับสนุนพร้อมกับระบบอัตโนมัติของการสำรองข้อมูลจะทำให้บล็อกโพสต์ดีหรือไม่? ฉันยังสามารถเพิ่มแผนภูมิ D3 บางส่วนเพื่อแสดงรายละเอียดของข้อมูลที่สมบูรณ์และไม่สมบูรณ์ ฉันยังสามารถเพิ่มคอลัมน์ if สำหรับประเภทของปัญหา จากนั้นแสดงรายละเอียดของประเภทด้วย
> 
> _โพสต์ดั้งเดิมโดย@mjhea0ใน[#47 (ความคิดเห็น)](https://github.com/jlord/sheetsee.js/pull/47#issuecomment-44542542)_
