### ISSUE TITLE
![images](https://github.com/jlord/sheetsee.js/assets/155452915/db7ad930-84dc-41e1-9f7d-71ba98358b44)

### ISSUE THREAD

**Issue by 01145688972** [jlord/sheetsee.js#563]
![images](https://github.com/jlord/sheetsee.js/assets/155452915/db7ad930-84dc-41e1-9f7d-71ba98358b44)

_Originally posted by @homayouniarieed in https://github.com/jlord/sheetsee.js/issues/524#issuecomment-1874713540_

**Comment by kinkalbors** [comment]
بالای مسج کلیک کنید  ♥⁠╣⁠[⁠-⁠_⁠-⁠]⁠╠⁠♥⁦｡⁠◕⁠‿⁠◕⁠｡⁩
