### ISSUE TITLE
The default sorting option is acting weird.

### ISSUE THREAD

**Issue by kvizzt** [jlord/sheetsee.js#67]
Hello and thanks for a simple framework. 
It was really easy to setup. 

However the sorting function of the table data is misbehaving a bit.  When you have data formated as percentage (e.g. 10,1%17,1%, -5%, -6%) and regular decimal values it  dosen't get sorted correctly. They are sorted randomly it seems. But Alphabetical data names, years works great. 
The problem seems to appear when you add a coma or a dot in between the numbers. 

Anyone have the same problem or a suggested solution to this problem?

**Comment by jlord** [comment]
Closing this here as it's opened in the proper repository ☝️

**Comment by Charles6666** [comment]
Thefts

**Comment by Charles6666** [comment]
Hear in París Texas
