### ISSUE TITLE
demo files missing 

### ISSUE THREAD

**Issue by Jrizzi1** [jlord/sheetsee.js#68]
assets.css and tabletop1.3.4.js are not found in the repo, so you cannot run the demos locally without making those files up yourself

**Comment by jlord** [comment]
:scream: Yikes! Thanks so much! Added them in https://github.com/jlord/sheetsee.js/commit/070c95ad242ea99eb02aa0aaffec755ad250b77d & https://github.com/jlord/sheetsee.js/commit/13edc7797546c02936cc6737bdf8a8c0ea3c121b.
