### ISSUE TITLE
Why do I open the index.html is very slow

### ISSUE THREAD

**Issue by 1029131145** [jlord/sheetsee.js#69]
Import CSS or JS is the external?

**Comment by kiranvenkat** [comment]
Hey jlord/sheetsee.,

Discover high quality jobs and connect with recruiters on LinkedIn.

- KIRAN

Accept invite: https://www.linkedin.com/e/v2?e=0-ip6cofrj-5r&t=ssuw&ek=invite_guest&li=44&m=invite_guest&ts=india_a&sharedKey=5yUYdqnd&invitationId=6146159284926369792



You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ip6cofrj-5r&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQE70BbvTHTDdAAAAVUuLd4IqQKDg9dHpDyap3XPhNF5atGZNIfPhaQSaEWuQ-f94pycaAK8GP4yK7NszfwfeXqA74PeJAI-UhvCs88zKuQKjaDCi-bt7GGgCNb6eOKLkCcYs3X-ktbbuQb-UoXpPLosJEOX6cnGuKik5GMXCR_tbXDwr3lfWAR8jnn76CQndyRF&eid=0-ip6cofrj-5r


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ip6cofrj-5r&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by kiranvenkat** [comment]
Hi Vishal,

The email address reply@reply.github.com was recently added to your LinkedIn account.

If you don&#39;t want that email associated with your account after all, here&#39;s how to remove it:

Type https://www.linkedin.com/e/v2?e=4m43lc-ip6wng17-vx&amp;t=nas&amp;midToken=AQElLUkRSpvYCA&amp;ek=security_add_email_notification into your browser
Sign in with your email address and password
Find Primary email in the upper left and click Change/Add
Click Remove next to the email address you&#39;re removing.

Thanks for using LinkedIn and for helping us to keep your account secure.
The LinkedIn Team



&copy; 2016 LinkedIn Ireland Limited. LinkedIn, the LinkedIn logo, and InMail are registered trademarks of LinkedIn Corporation in the United States and/or other countries. All rights reserved.



This email was intended for Vishal Sharma (Student at Maharaja Agrasen Institute Of Technology). 
Learn why we included this: https://www.linkedin.com/e/v2?e=4m43lc-ip6wng17-vx&a=customerServiceUrl&midToken=AQElLUkRSpvYCA&ek=security_add_email_notification&articleId=4788

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=4m43lc-ip6wng17-vx&a=customerServiceUrl&midToken=AQElLUkRSpvYCA&ek=security_add_email_notification

LinkedIn is a registered business name of LinkedIn Ireland Limited.
Registered in Ireland as a private limited company, Company Number 477441
Registered Office: Wilton Plaza, Wilton Place, Dublin 2, Ireland

**Comment by 1029131145** [comment]
oh my god，It has been over two years.
