### ISSUE TITLE
Marker Clustering

### ISSUE THREAD

**Issue by brianmcdonald** [jlord/sheetsee.js#71]
Sheetsee has been fantastic for mapping data I'm using but a lot of the datapoints have the exact same coordinates which will require me to apply some sort of marker clustering.

I tried working with mapbox.js clustering alongside sheetsee but had no joy. Is marker clustering something that can be done with sheetsee or is it unsupported?

**Comment by jlord** [comment]
Hiya!

Were you able to figure it out from the hack-spots repo? It was added with this PR: https://github.com/jlord/hack-spots/pull/11.

It would be great if it were an option in sheetsee, I have the same-location problem on a lot of stuff too.

**Comment by jlord** [comment]
This was added to `sheetsee-maps` via ☝️ ✨
