### ISSUE TITLE
Sheetsee-bubble comes up with empty page

### ISSUE THREAD

**Issue by bjayaram** [jlord/sheetsee.js#81]
Hi,

I tried the bubble chart at https://github.com/maxogden/sheetsee-d3bubble (which btw, I hosted at http://www.wyzpubs.com/dataviz/sheetsee/sheetsee-d3bubble/) and it results in an empty page. If I use div: 'body' instead of div: '#stuff' in index.html, it works. How do I make the svg element be contained within the div 'stuff'?

Thanks,
Jayaram

**Comment by jlord** [comment]
I'm not sure, I haven't looked at that project in a long, long time and unfortunately can't offer any support. I did just look at it briefly and it seems the spreadsheet isn't working (it probably no longer exists) on your example and in the repo itself.

**Comment by bjayaram** [comment]
I believe this may have something to do with the fact that the spreadsheet is in the old Google sheet format - don't know for sure. I did get the bubble chart to work for me as I am able to embed it in this post - http://www.wyzpubs.com/wp/2015/10/09/using-sheetsee-js-to-visualize-app-data/
There is still a minor annoyance though in that the chart does not appear in the iframe the first time the page loads, a page refresh is still required.
