### ISSUE TITLE
Popup Content Formatting

### ISSUE THREAD

**Issue by jlord** [jlord/sheetsee.js#9]
I finally [found a way](https://github.com/jllord/sheetsee.js/blob/gh-pages/js/sheetsee.js#L235-L261), and am so very proud, to let users send in custom content to add to the geoJSON (that they'll later call upon when formatting marker popup content). 

I can't, however, figure out a good way to have users pass in the format for popup content since it will depend on feature.opt and so forth which won't be defined outside of sheetsee.js. I had one sort of loose idea but it involved regular expressions and seemed not ideal. 

I was thinking, maybe I should just have users bring the entire [addPopup()](https://github.com/jllord/sheetsee.js/blob/gh-pages/js/sheetsee.js#L235-L261) function into their HTML instead of having them pass something from the HTML into addPopup() in sheetsee. It's not a huge function and at this point seems like the easiest way to handle things. 

/ cc @maxogden

**Comment by Ame93** [comment]
Summary
